from typing import Annotated, Any, Literal
from typing_extensions import TypedDict
from pydantic import BaseModel, Field

from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages
from assist_runtime.runtime.context import ExecutionContext


class PlanStep(BaseModel):

    step_id: int = Field(
        description="Unique ordered index"
    )

    task: str = Field(
        description="Description of task"
    )

    tool_suggested: str | None = Field(
        default=None,
        description="Tool required for this step"
    )

    tool_input: dict[str, Any] | None = Field(
        default=None,
        description="Structured arguments for tool execution"
    )

    status: Literal[
        "pending",
        "running",
        "completed",
        "failed"
    ] = "pending"


class ExecutionPlan(BaseModel):
    """The structured strategy generated by the planner LLM."""
    objective: str = Field(description="The final goal the agent is trying to achieve")
    steps: list[PlanStep] = Field(default_factory=list, description="Sequential list of steps to execute")
    revised_count: int = Field(0, description="Tracks how many times this plan has been replanned/healed")

class GraphState(TypedDict):

    input_text: str

    context: ExecutionContext

    messages: Annotated[
        list[AnyMessage],
        add_messages
    ]

    current_plan: ExecutionPlan | None

    current_step_index: int

    selected_tool: str | None

    tool_input: dict[str, Any] | None

    tool_output: dict[str, Any] | str | list | None

    current_iteration: int

    max_iterations: int

    is_complete: bool

    next_node: str | None

    error: str | None

    final_response: str | None